simulator_config:
  scene: 'FloorPlan3'
llm_config:
  human_task: '
  Your Task is:
  - search for the apple.
  - put the apple in the fridge.
  '
  model: 'gpt-4o'
  system_task: '
  - You will control a Robot inside the simulator.
  - You will be given a task to do inside the simulator.
  - Use the simulator actions to control the robot and fullfill your task.
  - After executing each action you will be presented by an Environment state.
  - A human will also provide you with a screenshot from the simulator.
  - After completing your task invoke the Done action.
  - With each message also explain your reasoning while executing each action.
  - A human will provide you with a screenshot from the simulator at the start of the episode.
  - You can only call one action at a time.
  - You must be less than 1.5 meters from an object to be able to interact with it.
  '