simulator_config:
  scene: 'FloorPlan3'
llm_config:
  human_task: '
  Your Task is:
  - pick up the potato.
  - put it in the pot.
  - pick up the pot.
  - go and stand IN FRONT OF the "StoveBurner", So that you are FACING IT DIRECTLY.
  - put the pot on the "StoveBurner". 
  - toggle the "StoveKnob" that is located on your far right.
  '
  model: 'gpt-4o-2024-11-20'
  system_task: '
  - You will control a Robot inside the simulator.
  - You will be given a task to do inside the simulator.
  - Use the simulator actions to control the robot and fullfill your task.
  - After executing each action you will be presented by an Environment state.
  - A human will also provide you with a screenshot from the simulator.
  - After completing your task invoke the Done action.
  - With each message also explain your reasoning while executing each action.
  - A human will provide you with a screenshot from the simulator at the start of the episode.
  - You can only call one action at a time.
  - You must be less than 1.5 meters from an object to be able to interact with it.
  - An Item will be in the visible items when it is less than 1.5 meters from the agent, and there is no other items obstructs the agent view.
  - If you see an object in the simulator screenshot, but it is not in the visible_objects list then you will need to approach the object to be able to interact with it.
  - Do NOT make up object_ids wait till you are less than 1.5 meters, you are aligned correctly with an object and, the object in the visible_objects list then use the object_id from this list visible_objects to ineract with it.
  '